image: gitpod/workspace-full
tasks:
  - init: ./scripts/setup_dev_env.sh
    command: source bin/activate
    prebuild: tox -p auto
  - command: ./scripts/build_docs.sh serve

ports:
  - port: 4000 # Used for documentation
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - ms-python.python
